name: release
on:
  push:
    branches:
      - main
  pull_request_target:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  release:
    if: "!startsWith(github.head_ref, 'release-please')"
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release-please.outputs.releases_created }}
      tag_name: ${{ steps.release-please.outputs.tag_name }}
    steps:
      - name: 运行 release-please-action
        id: release-please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json

  build:
    needs: release
    uses: ./.github/workflows/build.yaml

  publish-to-release:
    runs-on: ubuntu-latest
    needs: [release, build]
    if: needs.release.outputs.releases_created == 'true'
    steps:
      - name: 导入构建产物
        uses: dawidd6/action-download-artifact@v11
        with:
          skip_unpack: true

      - name: 发布到Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ needs.release.outputs.tag_name }}
          tag_name: ${{ needs.release.outputs.tag_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          files: MuseTUI-*
